development:
  adapter: sqlite3
  database: adopt_a_dog_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: adopt_a_dog_test
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb
  pool: 5
  timeout: 5000
